version: "3.9"

services:
  db:
    image: "postgres"
    container_name: pgdb
    # command: node run migrate
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: docker
    volumes:
      - data:/var/lib/postgresql/data
  dbadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  mwserver:
    container_name: mwserver
    build: .
    volumes:
      - ./:/app
      - ./app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  data:
  pgadmin-data:
